FROM nginx:stable-alpine

# Remove config padrão
RUN rm -f /etc/nginx/conf.d/default.conf

# Copia o build do Vite
COPY dist /usr/share/nginx/html

# Copia config customizada (sem HTTPS)
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
